// List of race names
export default [
   "Aarakocra",
   "Aasimar",
   "Bugbear",
   "Centaur",
   "Changling",
   "Dragonborn",
   "Dwarf",
   "Elf",
   "Feral Tiefling",
   "Firbolg",
   "Genasi",
   "Gith",
   "Gnome",
   "Goblin",
   "Goliath",
   "Half-Elf",
   "Half-Orc",
   "Halfling",
   "Hobgoblin",
   "Human",
   "Kalashtar",
   "Kenku",
   "Kobold",
   "Lizardfolk",
   "Loxodon",
   "Minotaur",
   "Orc",
   "Shifter",
   "Simic Hybrid",
   "Tabaxi",
   "Tiefling",
   "Tortle",
   "Triton",
   "Vedalken",
   "Verdan",
   "Warforged",
   "Yuan-ti Pureblood"
]